# Generated by Django 6.1.1 on 2026-10-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_passkeycredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20),
        ),
    ]
