# Generated by Django 6.1.1 on 2026-10-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_recurringtransaction_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passkeycredential',
            name='credential_id',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='passkeycredential',
            name='public_key',
            field=models.TextField(),
        ),
    ]
